---

- debug:
    msg: "Dentro del rol"
  tags:
    - cartel

- name: "Mostrando facts - No incluir"
  include_tasks: _otros/otros.yml
  tags:
    - never
    - otros

- debug:
    msg: "archivo a incluir Nro: {{ NroPrueba }}"


- name: "Incluyo archivo prueba_NroPrueba"
  include_tasks: prueba_{{ NroPrueba }}.yml

