---

- debug:
    msg: "Dentro prueba_1"

- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts

- copy:
    content: "{{ ansible_facts | to_nice_json }}"
    dest: "/tmp/ansible_facts.json"

