---


- name: "Parciando listado de grupos secundarios: LIST_USUARIOS.GROUPS "
  set_fact: foo_item="{{ item.GROUPS.split(',') }}"
  with_items: "{{ LIST_USUARIOS  }}"
  register: foo_result
  tags:
    - Alta-Usuarios

- name: "Cargando listado GruposToCreate"
  set_fact: GruposToCreate="{{ foo_result.results | map(attribute='ansible_facts.foo_item') | list }}"
  tags:
    - Alta-Usuarios

- name: "Alta de groups Secundarios del usuario "
  become: yes
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ GruposToCreate }}"
  tags:
    - Alta-Usuarios

- name: "Agregando group Primario del usuario "
  become: yes
  group:
    name: "{{ item.USERNAME }}"
    state: present
  with_items: "{{ LIST_USUARIOS }}"
  tags:
    - Alta-Usuarios

    
- name: "Alta y/o Actualizacion del usuario"
  become: yes
  user:
    name: "{{ item.USERNAME }}"
    password: "{{ item.HASH }}"
    group: "{{ item.USERNAME }}"
    groups: "{{item.GROUPS}}"
    state: present
    append: yes
  with_items: "{{ LIST_USUARIOS }}"
  tags:
    - Alta-Usuarios


# - debug:
#     msg: " contenido del archivo: {{ lookup('file','files/{{ item.USERNAME }}.pub') }}"
#   with_items: "{{ LIST_USUARIOS }}"
#   ignore_errors: yes
#   tags:
#     - SSH-KEY

- name: "Add Clave Publica en authorized"
  become: yes
  authorized_key:
    user: "{{ item.USERNAME }}"
    key: "{{ lookup('file', 'files/{{ item.USERNAME }}.pub' , errors='ignore') }}"
    state: present
  with_items: "{{ LIST_USUARIOS }}"
#  ignore_errors: yes
  tags:
    - SSH-KEY
